# Import the json module to work with JSON data
import json
# Import the AzureOpenAI class from the openai module to interact with the Azure OpenAI service
from openai import AzureOpenAI
# Import the os module to access environment variables
import os
# Import streamlit to access secrets stored in Streamlit's secure storage when deployed
import streamlit as st
# Import the load_dotenv function from the dotenv module to load environment variables from a .env file
from dotenv import load_dotenv

# Load environment variables from a .env file to access sensitive information like API keys
load_dotenv()

# Define the NegotiationAgent class, which is responsible for converting contract risks into negotiation recommendations
class NegotiationAgent:
    """
    The NegotiationAgent accepts structured JSON output from the RiskAnalysisAgent
    and converts identified contract risks into negotiation positions, proposed
    revised language, fallback positions, and business rationale.
    """

    # Initialize the NegotiationAgent class, setting up the Azure OpenAI client and loading necessary environment variables
    def __init__(self):
        self.client = AzureOpenAI(
            api_key=os.getenv("AZURE_OPENAI_API_KEY") or st.secrets.get("AZURE_OPENAI_API_KEY"),
            api_version=os.getenv("AZURE_OPENAI_API_VERSION") or st.secrets.get("AZURE_OPENAI_API_VERSION"),
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT") or st.secrets.get("AZURE_OPENAI_ENDPOINT")
        )

        # Load the deployment name for the Azure OpenAI model from environment variables
        self.deployment_name = os.getenv("AZURE_OPENAI_DEPLOYMENT") or st.secrets.get("AZURE_OPENAI_DEPLOYMENT")

        print("Negotiation Agent initialized")

    # Define the run method, which accepts the output from the RiskAnalysisAgent and returns negotiation recommendations
    def run(self, risk_results):
        """
        Accepts the RiskAnalysisAgent output as a Python dictionary
        and returns negotiation recommendations as a Python dictionary.
        """

        # Validate that the input risk_results is a dictionary and contains the expected 'risks' key
        if not isinstance(risk_results, dict):
            raise TypeError("risk_results must be a Python dictionary.")

        # Validate that the 'risks' key is present in the risk_results dictionary
        if "risks" not in risk_results:
            raise ValueError("risk_results must contain a 'risks' key.")

        system_message = """
You are a contract negotiation strategy agent for Sterling Legal Partners.

Your job is to review structured contract risk analysis results and recommend practical negotiation improvements.

You must:
- Use only the risks provided in the input JSON.
- Do not invent new risks.
- Do not invent citations.
- Recommend revised contract language for each risk.
- Explain the negotiation strategy in business-friendly language.
- Prioritize high-severity risks first.
- Return ONLY valid JSON.
- Do not include markdown.
- Do not include commentary outside the JSON.

Return JSON using this exact structure:

{
  "negotiation_overview": "",
  "negotiation_items": [
    {
      "risk_title": "",
      "severity": "",
      "category": "",
      "citation": "",
      "negotiation_position": "",
      "proposed_language": "",
      "fallback_position": "",
      "business_rationale": ""
    }
  ],
  "priority_order": [],
  "recommended_negotiation_strategy": ""
}
"""
        # Agent to agent communication: The NegotiationAgent receives structured risk analysis output from the 
        # RiskAnalysisAgent and generates negotiation recommendations based on that input. 
        user_message = f"""
Here is the structured risk analysis output from the RiskAnalysisAgent:

{json.dumps(risk_results, indent=2)}

Create negotiation recommendations based only on this input.
"""
        # Make a request to the Azure OpenAI API to generate negotiation recommendations based on the 
        # provided risk analysis results
        response = self.client.chat.completions.create(
            model=self.deployment_name,
            messages=[
                {"role": "system", "content": system_message},
                {"role": "user", "content": user_message}
            ],
            
        )
        # Extract the raw response content from the Azure OpenAI API response, which contains the negotiation 
        # recommendations generated by the model
        raw_response = response.choices[0].message.content

        # Attempt to parse the raw response as JSON; if parsing fails, print the raw response for debugging
        try:
            result = json.loads(raw_response)
        except json.JSONDecodeError as e:
            print("Raw model response was not valid JSON:")
            print(raw_response)
            raise e

        return result